### ISSUE TITLE
Swiper

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#475]
### Описание бага

В наших проектах не проходит `typecheck` при использовании глобально реакта версии 18 - https://github.com/atls-academy/Mirved64.github.io/pull/11#discussion_r1281445752

Причина - необходимо создавать дубликаты `@types/react`, что провоцирует ошибки дубликатов зависимостей.

### Воспроизведение

1. Создать проект с глобальным `react` версии 18
2. Использовать `@atls-ui-parts/swiper` в зависимостях
3. В `.yarnrc.yaml` добавить:
```yaml
packageExtensions:
...
  swiper@*:
    dependencies:
      '@types/react': '17.0.62'
      react: '17.0.2'
```

### Ожидаемое поведение

Нет ошибок при `typecheck`.

### Материалы

Ошибка дубликата `@types/react` 17 и 18:
```shell
➤ YN0000: │ ../../../../../.yarn/berry/cache/@types-react-npm-18.2.18-cb58ec5c01-9.zip/node_modules/@types/react
➤ YN0000: │ /ts5.0/index.d.ts
➤ YN0000: │
➤ YN0000: │   Error: Duplicate identifier 'LibraryManagedAttributes'.
```

### Данные окружения

- macOS 13.4.1
