### ISSUE TITLE
Исправление зависимостей пакетов

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#527]
### С чем связан запрос на фичу?

Необходимо добавить недостающие зависимости в UI компоненты для уменьшения пользования `packageExtensions` в проектах

### Расскажите как вы это себе видите

Необходимо пройтись по нашим проектам и собрать все случаи когда нашим пакетам даются зависимости из `yarnrc.yml` через `packageExtension`. Список будет дополнятся:

## Garnet

```yaml
  '@atls-utils/use-hover@*':
    dependencies:
      react-dom: '18.2.0'
  '@atls-ui-proto/avatar@0.]0.11':
    dependencies:
      '@stitches/react': '1.2.8'
  '@atls-ui-parts/text@0.0.12':
    dependencies:
      '@types/styled-system': '5.1.20'
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '11.9.0'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-proto/avatar@*':
    peerDependencies:
      react-dom: '*'
```

## Drum in:

повтор выше

## Delta:

```yaml
  '@atls-ui-parts/layout@*':
    dependencies:
      '@emotion/styled': '*'
      csstype: '*'
      styled-system: '*'
  '@atls-ui-parts/text@*':
    dependencies:
      '@emotion/styled': '*'
      styled-system: '*'
  '@atls-ui-proto/layout@*':
    dependencies:
      react: '*'
  '@atls-ui-proto/text@*':
    dependencies:
      react: '*'
```

## Misik:

повтор выше

### Definition of done (критерий готовности)

Зависимости добавлены, компоненты рендерятся и работают
